apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "workshop"
  namespace: securecodebox-system
  annotations:
    metadata.scan.securecodebox.io/git-repo-url: "https://github.com/newsupapat/gitleak-workshop"
    defectdojo.securecodebox.io/product-name: 'workshop-01'
    defectdojo.securecodebox.io/product-type-name: 'WORKSHOP'
spec:
  scanType: "gitleaks"
  volumes:
    - name: repo
      emptyDir: {}
  volumeMounts:
    - name: repo
      mountPath: "/repo/"
  initContainers:
    - name: "git-clone"
      image: bitnami/git
      volumeMounts:
        - name: repo
          mountPath: "/repo/"
      command:
        - git
        - clone
        - '--mirror'
        - 'https://github.com/newsupapat/gitleak-workshop.git'
        - /repo/
  parameters:
    - "detect"
    - "--source"
    - "/repo/"
